name: frontend_404dungeon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  animated_cards_carousel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

